# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
# Personal info
name: Girish Mohan
title: Undergraduate at Manipal Institute of Technology
email: mohangiri1999@gmail.com
resume: https://drive.google.com/file/d/1LQJt9oqfnBAN2xJqcIZEyPBUNlOsrGLF/view?usp=sharing

# Social links
twitter_username: girish_m_m
github_username:  girishmm
facebook_username: girishmohan1999
linkedin_username: girishmm

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Girish, a senior year Information Technology undergrad at the Manipal Institute of 
  Technology. My research interests primarily lie in Computational Neuroscience. I am currently 
  looking for opportunities to work on a project in this area. The things that I currently have 
  the most experience working with are:
  <mark>Javascript</mark>,
  <mark>Angular</mark>
  <mark>Java</mark>,
  <mark>Python</mark>,
  <mark>Android</mark>,
  <mark>Swift</mark>, and
  <mark>Matlab</mark>.
  
  A proud Tamizhan hailing from Madurai, I spend my leisure time cycling to 
  new destinations or playing the violin.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  When I'm not at my desk I am very active and spend most of my time outdoors. During my time at Uni 
  I have become a very keen marathoner. In 2018 I participated in my first half-marathon and completed 
  it in sub two hours. In the rest of my free time you will either find me working on my bikes, 
  playing at one of Manipal's basketball courts or down the football field.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
